services:
  app:
    build:
      context: .
    container_name: social_media_app
    env_file:
      - .env
    environment:
      STATIC_ROOT: /files/static
      MEDIA_ROOT: /files/media
    ports:
      - "8000:8000"
    volumes:
      - media_data:/files/media
      - static_data:/files/static
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:17.6-alpine
    container_name: social_media_postgres
    env_file:
      - .env
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:${PGDATA}
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: social_media_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
    container_name: social_media_celery_worker
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A social_media_api worker -l INFO"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  flower:
    build:
      context: .
    container_name: social_media_flower
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A social_media_api flower --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
  static_data:
